// Code generated by cmd/cgo; DO NOT EDIT.

//line /mnt/e/Projects/Final Year Project/ONDC-Gateway/c_go_http/request.go:1:1
package main

import _ "unsafe"
import (
   "io/ioutil"
   "log"
   "net/http"
)

//export get
func get() * /*line :11:13*/_Ctype_char /*line :11:19*/ {
	resp, err := http.Get("https://jsonplaceholder.typicode.com/posts")
	if err != nil {
      log.Fatalln(err)
	}
	
	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		log.Fatalln(err)
	}

	var cstr * /*line :22:12*/_Ctype_char /*line :22:18*/ 

	sb := string(body)
	cstr = ( /*line :25:9*/_Cfunc_CString /*line :25:17*/)(sb)

	return cstr
}

func main() {
}